### PR TITLE
Implements skip option or skipLaunch4j property

### LINKED ISSUE #189: need a configuration option to skip plugin
It is typical and even expected for Maven plugins to have a `<skip>` option, so that we can provide (via properties, profiles, etc.) a way to skip the plugin execution. See for example the [Antrun Plugin `<skip>` option](https://maven.apache.org/plugins/maven-antrun-plugin/run-mojo.html#skip) and the [Maven Assembly Plugin `<skipAssembly>` option](https://maven.apache.org/plugins/maven-assembly-plugin/single-mojo.html#skipAssembly). (I could provide a long list of similar plugins.)

Please provide a Maven configuration option to skip execution of this plugin.

### PR DESCRIPTION
**Pull request by lukaszlenart**
You can either use `<skip>true</skip>` in the configuration or provide `-DskipLaunch4j` property to JVM.

Closes #189

### CODE REVIEW

**Comment by lukaszlenart** [comment]
@garretwilson does it meet your requirements?

**Comment by garretwilson** [comment]
> @garretwilson does it meet your requirements?

Without testing it, it looks good. (See the typo I found above.)

**Comment by lukaszlenart** [comment]
> Without testing it, it looks like what I need. (See the typo I found above.)

typo?

**Comment by garretwilson** [comment]
I added a comment on line 802. Did it not show up?

**Comment by lukaszlenart** [comment]
> I added a comment on line 802. Did it not show up?

Nope, you must submit your review first

**Comment by lukaszlenart** [comment]
I found it, already fixed :)

**Comment by garretwilson** [comment]
> Nope, you must submit your review first

Oh! Good to know. (I've been reviewing using other platforms for the past few years.)

Well, looks like you already caught it anyway.

**Pull request merged**
